### PR TITLE
Merge pull request #1 from carpentry-instructor-training/master

### PR DESCRIPTION
**Pull request by melonsuper**
Hi, my name is Jinfang (Jane) Gao. I work at UQ as a researcher. My background is a bit complicated, bachelor in mathematics, master degree in numerical modeling and then a doctoral degree in geophysics. Now, part of my work involves software development (including parallel computing and numerical modeling) in coal mining and petroleum engineering.
And I'm interested in learning new stuff, especially software development, investment, and entrepreneurship. I went to the Software Carpentry Training in September this year, and I hope to be an instructor and help others as well.

### CODE REVIEW

**Comment by weaverbel** [comment]
Hi Jane
I merged that pull request but we still don’t have a text file for you in the master repo.
Can you please create a new text file in your fork and I will talk you through the pull request? Or I could come over and show you tomorrow.

Here is the text.

Hi, my name is Jinfang (Jane) Gao. I work at UQ as a researcher. My background is a bit complicated, bachelor in mathematics, master degree in numerical modeling and then a doctoral degree in geophysics. Now, part of my work involves software development (including parallel computing and numerical modeling) in coal mining and petroleum engineering.
And I'm interested in learning new stuff, especially software development, investment, and entrepreneurship. I went to the Software Carpentry Training in September this year, and I hope to be an instructor and help others as well.
Or come to Hacky Hour at St Lucy café today 4-5 pm. Sam and I will be able to help you.

Cheers
Belinda

**Comment by melonsuper** [comment]
Sorry Belinda, I just saw your comments. Can we meet tomorrow? I will be at UQ for the whole day. Can you please feel free to let me know what time suits you best? Thanks :+1:

**Comment by weaverbel** [comment]
Hi there
I am free all morning – where are you based? I am happy to pop in.
Cheers
Belinda

**Comment by melonsuper** [comment]
Hi Belinda,

I have tried to create a pull request again. Could you please have a 
look if it works now?

Thanks.
Jinfang

On 01/12/15 17:03, Belinda Weaver wrote:

> Hi there
> I am free all morning – where are you based? I am happy to pop in.
> Cheers
> Belinda
> 
> From: Jinfang Gao [mailto:notifications@github.com]
> Sent: Tuesday, 1 December 2015 4:56 PM
> To: carpentry-instructor-training/2016-01-18-training-prep
> Cc: Belinda Weaver
> Subject: Re: [2016-01-18-training-prep] Merge pull request #1 from 
> carpentry-instructor-training/master (#12)
> 
> Sorry Belinda, I just saw your comments. Can we meet tomorrow? I will 
> be at UQ for the whole day. Can you please feel free to let me know 
> what time suits you best? Thanks [:+1:]
> 
> —
> Reply to this email directly or view it on 
> GitHubhttps://github.com/carpentry-instructor-training/2016-01-18-training-prep/pull/12#issuecomment-160877469.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/carpentry-instructor-training/2016-01-18-training-prep/pull/12#issuecomment-160878609.

## 

Kind regards,
_Jinfang Gao_

## Postdoctoral Research Fellow

Centre for Geoscience Computing
School of Earth Sciences
The University of Queensland (UQ)
Brisbane, QLD 4072

W: Linkedin page https://www.linkedin.com/pub/jinfang-gao/67/99b/643
W: UQ Researchers http://researchers.uq.edu.au/researcher/11440

## Twitter: @Jane_UQ

**Comment by apawlik** [comment]
Hi Both,

Thanks for working on this.
Jane, if you can add a file with your name to your master repo (as per instructions specified below), the PR will update automatically.

Let me know if you need more help,
Aleksandra

"Your pull request should contain one file (and one file only) called "your_name.txt" (e.g., marie_curie.txt or alan_turing.txt). This file should contain a sentence or two that describes the type of work you do. You will submit the name of this file as part of your application. 
Help on creating pull requests can be found at https://help.github.com/articles/using-pull-requests."

**Comment by weaverbel** [comment]
I have merged it. Well done.
Regards
Belinda

**Pull request merged**
